interface Garment { id: number; nombre: string; categoria: string; talle: string; estado: string; ruta_imagen: string | null; disponible: boolean }
interface User { id: number; nombre: string; email: string; rol: 'admin' | 'usuario' }

const $ = <T extends HTMLElement>(selector: string): T => document.querySelector(selector) as T;
let currentUser: User | null = null;
let garments: Garment[] = [];
const toast = (message: string) => { const element = $('#toast'); element.textContent = message; element.classList.add('visible'); window.setTimeout(() => element.classList.remove('visible'), 3500); };
const api = async <T>(url: string, options: RequestInit = {}): Promise<T> => { const response = await fetch(`/api${url}`, { credentials: 'include', ...options }); const data = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(data?.error ?? 'No se pudo completar la acción.'); return data as T; };

function renderCatalog(): void {
  const query = $('#search').value.toLowerCase(); const category = $('#category').value.toLowerCase();
  const filtered = garments.filter((item) => (!query || `${item.nombre} ${item.categoria}`.toLowerCase().includes(query)) && (!category || item.categoria.toLowerCase() === category));
  $('#catalog').innerHTML = filtered.map((item) => `<article class="garment"><div class="garment-image">${item.ruta_imagen ? `<img src="${item.ruta_imagen}" alt="${item.nombre}">` : `<span class="garment-placeholder">${item.talle}</span>`}</div><div class="garment-info"><h3 class="garment-title">${item.nombre}</h3><div class="garment-meta"><span>${item.categoria}</span><span>Talle ${item.talle}</span></div><button class="button button-dark request-button" data-id="${item.id}">Solicitar prenda</button></div></article>`).join('');
  $('#empty').classList.toggle('hidden', filtered.length > 0);
  document.querySelectorAll<HTMLButtonElement>('.request-button').forEach((button) => button.addEventListener('click', () => requestGarment(Number(button.dataset.id))));
}
async function loadCatalog(): Promise<void> { try { const data = await api<{ prendas: Garment[] }>('/prendas'); garments = data.prendas; renderCatalog(); } catch (error) { toast((error as Error).message); } }
async function requestGarment(id: number): Promise<void> { if (!currentUser) { $('#auth-dialog').showModal(); toast('Ingresá para solicitar una prenda.'); return; } try { await api(`/prendas/${id}/solicitar`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({}) }); toast('Solicitud enviada correctamente.'); } catch (error) { toast((error as Error).message); } }
function updateSession(user: User | null): void { currentUser = user; $('#open-login').classList.toggle('hidden', Boolean(user)); $('#logout').classList.toggle('hidden', !user); $('#open-admin').classList.toggle('hidden', user?.rol !== 'admin'); $('#admin-panel').classList.toggle('hidden', user?.rol !== 'admin'); }
function setupAuth(): void { const dialog = $('#auth-dialog'); let registering = false; $('#open-login').addEventListener('click', () => dialog.showModal()); $('#close-login').addEventListener('click', () => dialog.close()); $('#toggle-auth').addEventListener('click', () => { registering = !registering; $('#auth-title').textContent = registering ? 'Crear cuenta' : 'Ingresar'; $('#name-field').classList.toggle('hidden', !registering); $('#toggle-auth').textContent = registering ? 'Ya tengo una cuenta' : '¿Todavía no tenés cuenta? Registrate'; $('#auth-submit').textContent = registering ? 'Registrarme' : 'Ingresar'; }); $('#auth-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget as HTMLFormElement); const payload = Object.fromEntries(form.entries()); try { const data = await api<{ user: User }>(registering ? '/auth/register' : '/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); updateSession(data.user); dialog.close(); toast(`Hola, ${data.user.nombre}.`); } catch (error) { $('#auth-message').textContent = (error as Error).message; } }); $('#logout').addEventListener('click', async () => { await api('/auth/logout', { method: 'POST' }); updateSession(null); toast('Sesión cerrada.'); }); }
function setupAdmin(): void { $('#open-admin').addEventListener('click', () => $('#admin-panel').scrollIntoView({ behavior: 'smooth' })); $('#garment-form').addEventListener('submit', async (event) => { event.preventDefault(); try { await api('/prendas', { method: 'POST', body: new FormData(event.currentTarget as HTMLFormElement) }); (event.currentTarget as HTMLFormElement).reset(); await loadCatalog(); toast('Prenda agregada al stock.'); } catch (error) { toast((error as Error).message); } }); }
async function bootstrap(): Promise<void> { setupAuth(); setupAdmin(); $('#search').addEventListener('input', renderCatalog); $('#category').addEventListener('change', renderCatalog); try { const data = await api<{ user: User }>('/auth/me'); updateSession(data.user); } catch { updateSession(null); } await loadCatalog(); }
void bootstrap();
