interface Garment { id: number; nombre: string; categoria: string; talle: string; estado: string; ruta_imagen: string | null; disponible: boolean }
interface User { id: number; nombre: string; email: string; rol: 'admin' | 'usuario' }
interface RequestItem { id: number; estado: 'pendiente' | 'aprobada' | 'rechazada'; mensaje: string | null; usuario_nombre: string; usuario_email: string; prenda_nombre: string }

const $ = <T extends HTMLElement>(selector: string): T => document.querySelector(selector) as T;
let currentUser: User | null = null;
let garments: Garment[] = [];
const toast = (message: string) => { const element = $('#toast'); element.textContent = message; element.classList.add('visible'); window.setTimeout(() => element.classList.remove('visible'), 3500); };
const api = async <T>(url: string, options: RequestInit = {}): Promise<T> => { const response = await fetch(`/api${url}`, { credentials: 'include', ...options }); const data = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(data?.error ?? 'No se pudo completar la acción.'); return data as T; };
const escapeHtml = (value: unknown): string => String(value ?? '').replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character] ?? character));

function renderCatalog(): void {
  const query = ($('#search') as HTMLInputElement).value.toLowerCase(); const category = ($('#category') as HTMLSelectElement).value.toLowerCase();
  const filtered = garments.filter((item) => (!query || `${item.nombre} ${item.categoria}`.toLowerCase().includes(query)) && (!category || item.categoria.toLowerCase() === category));
  $('#catalog').innerHTML = filtered.map((item) => `<article class="garment"><div class="garment-image">${item.ruta_imagen ? `<img src="${escapeHtml(item.ruta_imagen)}" alt="${escapeHtml(item.nombre)}">` : `<span class="garment-placeholder">${escapeHtml(item.talle)}</span>`}</div><div class="garment-info"><h3 class="garment-title">${escapeHtml(item.nombre)}</h3><div class="garment-meta"><span>${escapeHtml(item.categoria)}</span><span>Talle ${escapeHtml(item.talle)}</span></div><button class="button button-dark request-button" data-id="${item.id}">Solicitar prenda</button></div></article>`).join('');
  $('#empty').classList.toggle('hidden', filtered.length > 0);
  document.querySelectorAll<HTMLButtonElement>('.request-button').forEach((button) => button.addEventListener('click', () => requestGarment(Number(button.dataset.id))));
}
async function loadCatalog(): Promise<void> { try { const data = await api<{ prendas: Garment[] }>('/prendas'); garments = data.prendas; renderCatalog(); } catch (error) { toast((error as Error).message); } }
async function requestGarment(id: number): Promise<void> { if (!currentUser) { ($('#auth-dialog') as HTMLDialogElement).showModal(); toast('Ingresá para solicitar una prenda.'); return; } try { await api(`/prendas/${id}/solicitar`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({}) }); toast('Solicitud enviada correctamente.'); } catch (error) { toast((error as Error).message); } }
async function loadRequests(): Promise<void> { if (currentUser?.rol !== 'admin') return; try { const data = await api<{ solicitudes: RequestItem[] }>('/admin/solicitudes'); $('#requests').innerHTML = data.solicitudes.length ? data.solicitudes.map((item) => `<div class="request-row"><div><strong>${escapeHtml(item.prenda_nombre)}</strong><br><span>${escapeHtml(item.usuario_nombre)} · ${escapeHtml(item.usuario_email)}</span>${item.mensaje ? `<p>${escapeHtml(item.mensaje)}</p>` : ''}</div><select class="request-status" data-id="${item.id}" aria-label="Estado de la solicitud"><option value="pendiente" ${item.estado === 'pendiente' ? 'selected' : ''}>Pendiente</option><option value="aprobada" ${item.estado === 'aprobada' ? 'selected' : ''}>Aprobada</option><option value="rechazada" ${item.estado === 'rechazada' ? 'selected' : ''}>Rechazada</option></select></div>`).join('') : '<p class="empty">Todavía no hay solicitudes.</p>'; document.querySelectorAll<HTMLSelectElement>('.request-status').forEach((select) => select.addEventListener('change', () => updateRequest(Number(select.dataset.id), select.value))); } catch (error) { toast((error as Error).message); } }
async function updateRequest(id: number, estado: string): Promise<void> { try { await api(`/admin/solicitudes/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ estado }) }); toast('Solicitud actualizada.'); await loadRequests(); } catch (error) { toast((error as Error).message); await loadRequests(); } }
function updateSession(user: User | null): void { currentUser = user; $('#open-login').classList.toggle('hidden', Boolean(user)); $('#logout').classList.toggle('hidden', !user); $('#open-admin').classList.toggle('hidden', user?.rol !== 'admin'); $('#admin-panel').classList.toggle('hidden', user?.rol !== 'admin'); }
function setupTheme(): void { const toggle = $('#theme-toggle') as HTMLButtonElement; const saved = localStorage.getItem('roperito-theme'); const dark = saved ? saved === 'dark' : window.matchMedia('(prefers-color-scheme: dark)').matches; const apply = (isDark: boolean): void => { document.body.classList.toggle('theme-dark', isDark); toggle.setAttribute('aria-pressed', String(isDark)); toggle.setAttribute('aria-label', isDark ? 'Activar modo claro' : 'Activar modo oscuro'); $('#theme-icon').textContent = isDark ? '☾' : '☼'; $('#theme-label').textContent = isDark ? 'Modo oscuro' : 'Modo claro'; localStorage.setItem('roperito-theme', isDark ? 'dark' : 'light'); }; apply(dark); toggle.addEventListener('click', () => apply(!document.body.classList.contains('theme-dark'))); }
function setupAuth(): void { const dialog = $('#auth-dialog') as HTMLDialogElement; const form = $('#auth-form') as HTMLFormElement; const nameInput = ($('#name-field input') as HTMLInputElement); const passwordInput = $('#auth-password') as HTMLInputElement; const submit = $('#auth-submit') as HTMLButtonElement; const message = $('#auth-message'); let registering = false; const updateMode = (): void => { $('#auth-title').textContent = registering ? 'Crear cuenta' : 'Ingresar'; $('#auth-description').textContent = registering ? 'Registrate para solicitar prendas y recibir novedades de tus pedidos.' : 'Accedé para solicitar prendas y seguir tus pedidos.'; $('#name-field').classList.toggle('hidden', !registering); nameInput.required = registering; nameInput.disabled = !registering; passwordInput.autocomplete = registering ? 'new-password' : 'current-password'; $('#toggle-auth').textContent = registering ? 'Ya tengo una cuenta' : '¿Todavía no tenés cuenta? Registrate'; submit.textContent = registering ? 'Registrarme' : 'Ingresar'; message.textContent = ''; }; const openDialog = (): void => { message.textContent = ''; dialog.showModal(); }; $('#open-login').addEventListener('click', openDialog); $('#footer-login-link').addEventListener('click', (event) => { event.preventDefault(); openDialog(); }); $('#close-login').addEventListener('click', () => dialog.close()); $('#toggle-auth').addEventListener('click', () => { registering = !registering; updateMode(); }); $('#toggle-password').addEventListener('click', () => { const visible = passwordInput.type === 'text'; passwordInput.type = visible ? 'password' : 'text'; $('#toggle-password').textContent = visible ? 'Mostrar' : 'Ocultar'; $('#toggle-password').setAttribute('aria-pressed', String(!visible)); }); form.addEventListener('submit', async (event) => { event.preventDefault(); if (!form.reportValidity()) return; const payload: Record<string, string> = {}; new FormData(form).forEach((value, key) => { payload[key] = String(value); }); submit.disabled = true; submit.textContent = registering ? 'Creando cuenta...' : 'Ingresando...'; message.textContent = ''; try { const data = await api<{ user: User }>(registering ? '/auth/register' : '/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); updateSession(data.user); await loadRequests(); dialog.close(); form.reset(); toast(`Hola, ${data.user.nombre}.`); } catch (error) { message.textContent = (error as Error).message; } finally { submit.disabled = false; submit.textContent = registering ? 'Registrarme' : 'Ingresar'; } }); $('#logout').addEventListener('click', async () => { await api('/auth/logout', { method: 'POST' }); updateSession(null); $('#requests').replaceChildren(); toast('Sesión cerrada.'); }); updateMode(); }
function setupAdmin(): void { $('#open-admin').addEventListener('click', () => $('#admin-panel').scrollIntoView({ behavior: 'smooth' })); $('#garment-form').addEventListener('submit', async (event) => { event.preventDefault(); try { await api('/prendas', { method: 'POST', body: new FormData(event.currentTarget as HTMLFormElement) }); (event.currentTarget as HTMLFormElement).reset(); await loadCatalog(); toast('Prenda agregada al stock.'); } catch (error) { toast((error as Error).message); } }); }
async function bootstrap(): Promise<void> { setupTheme(); setupAuth(); setupAdmin(); $('#search').addEventListener('input', renderCatalog); $('#category').addEventListener('change', renderCatalog); try { const data = await api<{ user: User | null }>('/auth/me'); updateSession(data.user); if (data.user) await loadRequests(); } catch { updateSession(null); } await loadCatalog(); }
void bootstrap();
