interface Garment { id: number; nombre: string; categoria: string; talle: string; estado: string; ruta_imagen: string | null; disponible: boolean }
interface User { id: number; nombre: string; email: string; rol: 'admin' | 'usuario' }
interface RequestItem { id: number; estado: 'pendiente' | 'aprobada' | 'rechazada'; mensaje: string | null; usuario_nombre: string; usuario_email: string; prenda_nombre: string }

const $ = <T extends HTMLElement>(selector: string): T => document.querySelector(selector) as T;
let currentUser: User | null = null;
let garments: Garment[] = [];
const toast = (message: string) => { const element = $('#toast'); element.textContent = message; element.classList.add('visible'); window.setTimeout(() => element.classList.remove('visible'), 3500); };
const api = async <T>(url: string, options: RequestInit = {}): Promise<T> => { const response = await fetch(`/api${url}`, { credentials: 'include', ...options }); const data = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(data?.error ?? 'No se pudo completar la acción.'); return data as T; };
const escapeHtml = (value: unknown): string => String(value ?? '').replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character] ?? character));

function renderCatalog(): void {
  const query = ($('#search') as HTMLInputElement).value.toLowerCase(); const category = ($('#category') as HTMLSelectElement).value.toLowerCase();
  const filtered = garments.filter((item) => (!query || `${item.nombre} ${item.categoria}`.toLowerCase().includes(query)) && (!category || item.categoria.toLowerCase() === category));
  $('#catalog').innerHTML = filtered.map((item) => `<article class="garment"><div class="garment-image">${item.ruta_imagen ? `<img src="${escapeHtml(item.ruta_imagen)}" alt="${escapeHtml(item.nombre)}">` : `<span class="garment-placeholder">${escapeHtml(item.talle)}</span>`}</div><div class="garment-info"><h3 class="garment-title">${escapeHtml(item.nombre)}</h3><div class="garment-meta"><span>${escapeHtml(item.categoria)}</span><span>Talle ${escapeHtml(item.talle)}</span></div><button class="button button-dark request-button" data-id="${item.id}">Solicitar prenda</button></div></article>`).join('');
  $('#empty').classList.toggle('hidden', filtered.length > 0);
  document.querySelectorAll<HTMLButtonElement>('.request-button').forEach((button) => button.addEventListener('click', () => requestGarment(Number(button.dataset.id))));
}
async function loadCatalog(): Promise<void> { try { const data = await api<{ prendas: Garment[] }>('/prendas'); garments = data.prendas; renderCatalog(); } catch (error) { toast((error as Error).message); } }
async function requestGarment(id: number): Promise<void> { if (!currentUser) { ($('#auth-dialog') as HTMLDialogElement).showModal(); toast('Ingresá para solicitar una prenda.'); return; } try { await api(`/prendas/${id}/solicitar`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({}) }); toast('Solicitud enviada correctamente.'); } catch (error) { toast((error as Error).message); } }
async function loadRequests(): Promise<void> { if (currentUser?.rol !== 'admin') return; try { const data = await api<{ solicitudes: RequestItem[] }>('/admin/solicitudes'); $('#requests').innerHTML = data.solicitudes.length ? data.solicitudes.map((item) => `<div class="request-row"><div><strong>${escapeHtml(item.prenda_nombre)}</strong><br><span>${escapeHtml(item.usuario_nombre)} · ${escapeHtml(item.usuario_email)}</span>${item.mensaje ? `<p>${escapeHtml(item.mensaje)}</p>` : ''}</div><select class="request-status" data-id="${item.id}" aria-label="Estado de la solicitud"><option value="pendiente" ${item.estado === 'pendiente' ? 'selected' : ''}>Pendiente</option><option value="aprobada" ${item.estado === 'aprobada' ? 'selected' : ''}>Aprobada</option><option value="rechazada" ${item.estado === 'rechazada' ? 'selected' : ''}>Rechazada</option></select></div>`).join('') : '<p class="empty">Todavía no hay solicitudes.</p>'; document.querySelectorAll<HTMLSelectElement>('.request-status').forEach((select) => select.addEventListener('change', () => updateRequest(Number(select.dataset.id), select.value))); } catch (error) { toast((error as Error).message); } }
async function updateRequest(id: number, estado: string): Promise<void> { try { await api(`/admin/solicitudes/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ estado }) }); toast('Solicitud actualizada.'); await loadRequests(); } catch (error) { toast((error as Error).message); await loadRequests(); } }
function updateSession(user: User | null): void { currentUser = user; $('#open-login').classList.toggle('hidden', Boolean(user)); $('#logout').classList.toggle('hidden', !user); $('#open-admin').classList.toggle('hidden', user?.rol !== 'admin'); $('#admin-panel').classList.toggle('hidden', user?.rol !== 'admin'); }
function setupAuth(): void { const dialog = $('#auth-dialog') as HTMLDialogElement; let registering = false; $('#open-login').addEventListener('click', () => dialog.showModal()); $('#close-login').addEventListener('click', () => dialog.close()); $('#toggle-auth').addEventListener('click', () => { registering = !registering; $('#auth-title').textContent = registering ? 'Crear cuenta' : 'Ingresar'; $('#name-field').classList.toggle('hidden', !registering); $('#toggle-auth').textContent = registering ? 'Ya tengo una cuenta' : '¿Todavía no tenés cuenta? Registrate'; $('#auth-submit').textContent = registering ? 'Registrarme' : 'Ingresar'; }); $('#auth-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget as HTMLFormElement); const payload: Record<string, string> = {}; form.forEach((value, key) => { payload[key] = String(value); }); try { const data = await api<{ user: User }>(registering ? '/auth/register' : '/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); updateSession(data.user); await loadRequests(); dialog.close(); toast(`Hola, ${data.user.nombre}.`); } catch (error) { $('#auth-message').textContent = (error as Error).message; } }); $('#logout').addEventListener('click', async () => { await api('/auth/logout', { method: 'POST' }); updateSession(null); $('#requests').replaceChildren(); toast('Sesión cerrada.'); }); }
function setupAdmin(): void { $('#open-admin').addEventListener('click', () => $('#admin-panel').scrollIntoView({ behavior: 'smooth' })); $('#garment-form').addEventListener('submit', async (event) => { event.preventDefault(); try { await api('/prendas', { method: 'POST', body: new FormData(event.currentTarget as HTMLFormElement) }); (event.currentTarget as HTMLFormElement).reset(); await loadCatalog(); toast('Prenda agregada al stock.'); } catch (error) { toast((error as Error).message); } }); }
async function bootstrap(): Promise<void> { setupAuth(); setupAdmin(); $('#search').addEventListener('input', renderCatalog); $('#category').addEventListener('change', renderCatalog); try { const data = await api<{ user: User }>('/auth/me'); updateSession(data.user); await loadRequests(); } catch { updateSession(null); } await loadCatalog(); }
void bootstrap();
